// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/test.proto

package test.api.v1;

public interface ColorsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.api.v1.Colors)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.test.api.v1.Colors.Color color = 1;</code>
   */
  int getColorValue();
  /**
   * <code>.test.api.v1.Colors.Color color = 1;</code>
   */
  test.api.v1.Colors.Color getColor();
}
