// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/test.proto

package test.api.v1;

public interface FlatOuterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.api.v1.FlatOuter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.test.api.v1.FlatInner prop1 = 1;</code>
   */
  boolean hasProp1();
  /**
   * <code>.test.api.v1.FlatInner prop1 = 1;</code>
   */
  test.api.v1.FlatInner getProp1();
  /**
   * <code>.test.api.v1.FlatInner prop1 = 1;</code>
   */
  test.api.v1.FlatInnerOrBuilder getProp1OrBuilder();

  /**
   * <code>string prop2 = 2;</code>
   */
  java.lang.String getProp2();
  /**
   * <code>string prop2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getProp2Bytes();
}
