// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/test.proto

package test.api.v1;

public interface FlatInnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.api.v1.FlatInner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string prop1 = 1;</code>
   */
  java.lang.String getProp1();
  /**
   * <code>string prop1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getProp1Bytes();
}
