// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/test.proto

package test.api.v1;

/**
 * Protobuf type {@code test.api.v1.Outer}
 */
public  final class Outer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:test.api.v1.Outer)
    OuterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Outer.newBuilder() to construct.
  private Outer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Outer() {
    prop2_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Outer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            test.api.v1.Outer.Inner.Builder subBuilder = null;
            if (prop1_ != null) {
              subBuilder = prop1_.toBuilder();
            }
            prop1_ = input.readMessage(test.api.v1.Outer.Inner.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(prop1_);
              prop1_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            prop2_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return test.api.v1.Test.internal_static_test_api_v1_Outer_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return test.api.v1.Test.internal_static_test_api_v1_Outer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            test.api.v1.Outer.class, test.api.v1.Outer.Builder.class);
  }

  public interface InnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.api.v1.Outer.Inner)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string prop1 = 1;</code>
     */
    java.lang.String getProp1();
    /**
     * <code>string prop1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getProp1Bytes();
  }
  /**
   * Protobuf type {@code test.api.v1.Outer.Inner}
   */
  public  static final class Inner extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.api.v1.Outer.Inner)
      InnerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Inner.newBuilder() to construct.
    private Inner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Inner() {
      prop1_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Inner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              prop1_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.api.v1.Test.internal_static_test_api_v1_Outer_Inner_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.api.v1.Test.internal_static_test_api_v1_Outer_Inner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.api.v1.Outer.Inner.class, test.api.v1.Outer.Inner.Builder.class);
    }

    public static final int PROP1_FIELD_NUMBER = 1;
    private volatile java.lang.Object prop1_;
    /**
     * <code>string prop1 = 1;</code>
     */
    public java.lang.String getProp1() {
      java.lang.Object ref = prop1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prop1_ = s;
        return s;
      }
    }
    /**
     * <code>string prop1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProp1Bytes() {
      java.lang.Object ref = prop1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prop1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProp1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, prop1_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProp1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, prop1_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.api.v1.Outer.Inner)) {
        return super.equals(obj);
      }
      test.api.v1.Outer.Inner other = (test.api.v1.Outer.Inner) obj;

      boolean result = true;
      result = result && getProp1()
          .equals(other.getProp1());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROP1_FIELD_NUMBER;
      hash = (53 * hash) + getProp1().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.api.v1.Outer.Inner parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.api.v1.Outer.Inner parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.api.v1.Outer.Inner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.api.v1.Outer.Inner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.api.v1.Outer.Inner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.api.v1.Outer.Inner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.api.v1.Outer.Inner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.api.v1.Outer.Inner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.api.v1.Outer.Inner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.api.v1.Outer.Inner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.api.v1.Outer.Inner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.api.v1.Outer.Inner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.api.v1.Outer.Inner prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.api.v1.Outer.Inner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.api.v1.Outer.Inner)
        test.api.v1.Outer.InnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.api.v1.Test.internal_static_test_api_v1_Outer_Inner_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.api.v1.Test.internal_static_test_api_v1_Outer_Inner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.api.v1.Outer.Inner.class, test.api.v1.Outer.Inner.Builder.class);
      }

      // Construct using test.api.v1.Outer.Inner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        prop1_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.api.v1.Test.internal_static_test_api_v1_Outer_Inner_descriptor;
      }

      public test.api.v1.Outer.Inner getDefaultInstanceForType() {
        return test.api.v1.Outer.Inner.getDefaultInstance();
      }

      public test.api.v1.Outer.Inner build() {
        test.api.v1.Outer.Inner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public test.api.v1.Outer.Inner buildPartial() {
        test.api.v1.Outer.Inner result = new test.api.v1.Outer.Inner(this);
        result.prop1_ = prop1_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.api.v1.Outer.Inner) {
          return mergeFrom((test.api.v1.Outer.Inner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.api.v1.Outer.Inner other) {
        if (other == test.api.v1.Outer.Inner.getDefaultInstance()) return this;
        if (!other.getProp1().isEmpty()) {
          prop1_ = other.prop1_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.api.v1.Outer.Inner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.api.v1.Outer.Inner) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object prop1_ = "";
      /**
       * <code>string prop1 = 1;</code>
       */
      public java.lang.String getProp1() {
        java.lang.Object ref = prop1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          prop1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string prop1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProp1Bytes() {
        java.lang.Object ref = prop1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prop1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string prop1 = 1;</code>
       */
      public Builder setProp1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        prop1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string prop1 = 1;</code>
       */
      public Builder clearProp1() {
        
        prop1_ = getDefaultInstance().getProp1();
        onChanged();
        return this;
      }
      /**
       * <code>string prop1 = 1;</code>
       */
      public Builder setProp1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        prop1_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.api.v1.Outer.Inner)
    }

    // @@protoc_insertion_point(class_scope:test.api.v1.Outer.Inner)
    private static final test.api.v1.Outer.Inner DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.api.v1.Outer.Inner();
    }

    public static test.api.v1.Outer.Inner getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Inner>
        PARSER = new com.google.protobuf.AbstractParser<Inner>() {
      public Inner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Inner(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Inner> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Inner> getParserForType() {
      return PARSER;
    }

    public test.api.v1.Outer.Inner getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int PROP1_FIELD_NUMBER = 1;
  private test.api.v1.Outer.Inner prop1_;
  /**
   * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
   */
  public boolean hasProp1() {
    return prop1_ != null;
  }
  /**
   * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
   */
  public test.api.v1.Outer.Inner getProp1() {
    return prop1_ == null ? test.api.v1.Outer.Inner.getDefaultInstance() : prop1_;
  }
  /**
   * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
   */
  public test.api.v1.Outer.InnerOrBuilder getProp1OrBuilder() {
    return getProp1();
  }

  public static final int PROP2_FIELD_NUMBER = 2;
  private volatile java.lang.Object prop2_;
  /**
   * <code>string prop2 = 2;</code>
   */
  public java.lang.String getProp2() {
    java.lang.Object ref = prop2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      prop2_ = s;
      return s;
    }
  }
  /**
   * <code>string prop2 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProp2Bytes() {
    java.lang.Object ref = prop2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      prop2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (prop1_ != null) {
      output.writeMessage(1, getProp1());
    }
    if (!getProp2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, prop2_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (prop1_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProp1());
    }
    if (!getProp2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, prop2_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof test.api.v1.Outer)) {
      return super.equals(obj);
    }
    test.api.v1.Outer other = (test.api.v1.Outer) obj;

    boolean result = true;
    result = result && (hasProp1() == other.hasProp1());
    if (hasProp1()) {
      result = result && getProp1()
          .equals(other.getProp1());
    }
    result = result && getProp2()
        .equals(other.getProp2());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProp1()) {
      hash = (37 * hash) + PROP1_FIELD_NUMBER;
      hash = (53 * hash) + getProp1().hashCode();
    }
    hash = (37 * hash) + PROP2_FIELD_NUMBER;
    hash = (53 * hash) + getProp2().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static test.api.v1.Outer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test.api.v1.Outer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test.api.v1.Outer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test.api.v1.Outer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test.api.v1.Outer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static test.api.v1.Outer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static test.api.v1.Outer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static test.api.v1.Outer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static test.api.v1.Outer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static test.api.v1.Outer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static test.api.v1.Outer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static test.api.v1.Outer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(test.api.v1.Outer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code test.api.v1.Outer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test.api.v1.Outer)
      test.api.v1.OuterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.api.v1.Test.internal_static_test_api_v1_Outer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.api.v1.Test.internal_static_test_api_v1_Outer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.api.v1.Outer.class, test.api.v1.Outer.Builder.class);
    }

    // Construct using test.api.v1.Outer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (prop1Builder_ == null) {
        prop1_ = null;
      } else {
        prop1_ = null;
        prop1Builder_ = null;
      }
      prop2_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return test.api.v1.Test.internal_static_test_api_v1_Outer_descriptor;
    }

    public test.api.v1.Outer getDefaultInstanceForType() {
      return test.api.v1.Outer.getDefaultInstance();
    }

    public test.api.v1.Outer build() {
      test.api.v1.Outer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public test.api.v1.Outer buildPartial() {
      test.api.v1.Outer result = new test.api.v1.Outer(this);
      if (prop1Builder_ == null) {
        result.prop1_ = prop1_;
      } else {
        result.prop1_ = prop1Builder_.build();
      }
      result.prop2_ = prop2_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof test.api.v1.Outer) {
        return mergeFrom((test.api.v1.Outer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(test.api.v1.Outer other) {
      if (other == test.api.v1.Outer.getDefaultInstance()) return this;
      if (other.hasProp1()) {
        mergeProp1(other.getProp1());
      }
      if (!other.getProp2().isEmpty()) {
        prop2_ = other.prop2_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      test.api.v1.Outer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (test.api.v1.Outer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private test.api.v1.Outer.Inner prop1_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        test.api.v1.Outer.Inner, test.api.v1.Outer.Inner.Builder, test.api.v1.Outer.InnerOrBuilder> prop1Builder_;
    /**
     * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
     */
    public boolean hasProp1() {
      return prop1Builder_ != null || prop1_ != null;
    }
    /**
     * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
     */
    public test.api.v1.Outer.Inner getProp1() {
      if (prop1Builder_ == null) {
        return prop1_ == null ? test.api.v1.Outer.Inner.getDefaultInstance() : prop1_;
      } else {
        return prop1Builder_.getMessage();
      }
    }
    /**
     * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
     */
    public Builder setProp1(test.api.v1.Outer.Inner value) {
      if (prop1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        prop1_ = value;
        onChanged();
      } else {
        prop1Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
     */
    public Builder setProp1(
        test.api.v1.Outer.Inner.Builder builderForValue) {
      if (prop1Builder_ == null) {
        prop1_ = builderForValue.build();
        onChanged();
      } else {
        prop1Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
     */
    public Builder mergeProp1(test.api.v1.Outer.Inner value) {
      if (prop1Builder_ == null) {
        if (prop1_ != null) {
          prop1_ =
            test.api.v1.Outer.Inner.newBuilder(prop1_).mergeFrom(value).buildPartial();
        } else {
          prop1_ = value;
        }
        onChanged();
      } else {
        prop1Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
     */
    public Builder clearProp1() {
      if (prop1Builder_ == null) {
        prop1_ = null;
        onChanged();
      } else {
        prop1_ = null;
        prop1Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
     */
    public test.api.v1.Outer.Inner.Builder getProp1Builder() {
      
      onChanged();
      return getProp1FieldBuilder().getBuilder();
    }
    /**
     * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
     */
    public test.api.v1.Outer.InnerOrBuilder getProp1OrBuilder() {
      if (prop1Builder_ != null) {
        return prop1Builder_.getMessageOrBuilder();
      } else {
        return prop1_ == null ?
            test.api.v1.Outer.Inner.getDefaultInstance() : prop1_;
      }
    }
    /**
     * <code>.test.api.v1.Outer.Inner prop1 = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        test.api.v1.Outer.Inner, test.api.v1.Outer.Inner.Builder, test.api.v1.Outer.InnerOrBuilder> 
        getProp1FieldBuilder() {
      if (prop1Builder_ == null) {
        prop1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            test.api.v1.Outer.Inner, test.api.v1.Outer.Inner.Builder, test.api.v1.Outer.InnerOrBuilder>(
                getProp1(),
                getParentForChildren(),
                isClean());
        prop1_ = null;
      }
      return prop1Builder_;
    }

    private java.lang.Object prop2_ = "";
    /**
     * <code>string prop2 = 2;</code>
     */
    public java.lang.String getProp2() {
      java.lang.Object ref = prop2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prop2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string prop2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProp2Bytes() {
      java.lang.Object ref = prop2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prop2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string prop2 = 2;</code>
     */
    public Builder setProp2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      prop2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string prop2 = 2;</code>
     */
    public Builder clearProp2() {
      
      prop2_ = getDefaultInstance().getProp2();
      onChanged();
      return this;
    }
    /**
     * <code>string prop2 = 2;</code>
     */
    public Builder setProp2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      prop2_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:test.api.v1.Outer)
  }

  // @@protoc_insertion_point(class_scope:test.api.v1.Outer)
  private static final test.api.v1.Outer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new test.api.v1.Outer();
  }

  public static test.api.v1.Outer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Outer>
      PARSER = new com.google.protobuf.AbstractParser<Outer>() {
    public Outer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Outer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Outer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Outer> getParserForType() {
    return PARSER;
  }

  public test.api.v1.Outer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

