// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/test.proto

package test.api.v1;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_api_v1_Outer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_api_v1_Outer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_api_v1_Outer_Inner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_api_v1_Outer_Inner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_api_v1_FlatInner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_api_v1_FlatInner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_api_v1_FlatOuter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_api_v1_FlatOuter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_api_v1_Colors_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_api_v1_Colors_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017test/test.proto\022\013test.api.v1\"W\n\005Outer\022" +
      "\'\n\005prop1\030\001 \001(\0132\030.test.api.v1.Outer.Inner" +
      "\022\r\n\005prop2\030\002 \001(\t\032\026\n\005Inner\022\r\n\005prop1\030\001 \001(\t\"" +
      "\032\n\tFlatInner\022\r\n\005prop1\030\001 \001(\t\"A\n\tFlatOuter" +
      "\022%\n\005prop1\030\001 \001(\0132\026.test.api.v1.FlatInner\022" +
      "\r\n\005prop2\030\002 \001(\t\"Y\n\006Colors\022(\n\005color\030\001 \001(\0162" +
      "\031.test.api.v1.Colors.Color\"%\n\005Color\022\007\n\003r" +
      "ed\020\000\022\010\n\004blue\020\001\022\t\n\005green\020\002B\017\n\013test.api.v1" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_test_api_v1_Outer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_api_v1_Outer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_api_v1_Outer_descriptor,
        new java.lang.String[] { "Prop1", "Prop2", });
    internal_static_test_api_v1_Outer_Inner_descriptor =
      internal_static_test_api_v1_Outer_descriptor.getNestedTypes().get(0);
    internal_static_test_api_v1_Outer_Inner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_api_v1_Outer_Inner_descriptor,
        new java.lang.String[] { "Prop1", });
    internal_static_test_api_v1_FlatInner_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_api_v1_FlatInner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_api_v1_FlatInner_descriptor,
        new java.lang.String[] { "Prop1", });
    internal_static_test_api_v1_FlatOuter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_test_api_v1_FlatOuter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_api_v1_FlatOuter_descriptor,
        new java.lang.String[] { "Prop1", "Prop2", });
    internal_static_test_api_v1_Colors_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_test_api_v1_Colors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_api_v1_Colors_descriptor,
        new java.lang.String[] { "Color", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
